version: '3.4'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./docker/php
    container_name: php
    volumes:
      - .:/var/www/project
  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: blog
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8000:80
    volumes:
      - /sessions
    external_links:
      - mysql:db
