index:
  - action: index
    path: /
    methods: GET
posts:
  - action: list
    path: '[/{page:[\d+]}]'
    methods: GET
  - action: show
    path: /{id:[a-z0-9-]+}
    methods: GET
comments:
  - action: create
    path: /create
    methods: POST
admin:
  - action: index
    path: ''
    methods: GET
  - action: readPosts
    path: /posts
    methods: GET
  - action: createPost
    path: /posts/create
    methods: GET | POST
  - action: readPost
    path: /posts/{id:\d+}
    methods: GET
  - action: updatePost
    path: /posts/edit/{id:\d+}
    methods: GET | POST
  - action: deletePost
    path: /posts/delete
    methods: POST
  - action: readComments
    path: /comments
    methods: GET
  - action: readComment
    path: /comments/edit/{id:\d+}
    methods: GET
  - action: updateComment
    path: /comments/edit/{id:\d+}
    methods: POST
  - action: readUsers
    path: /users
    methods: GET
  - action: readUser
    path: /users/{id:\d+}
    methods: GET
  - action: updateUser
    path: /users/edit/{id:\d+}
    methods: GET | POST
  - action: deleteUser
    path: /users/delete
    methods: POST
  - action: readSocialNetWorks
    path: /social-networks
    methods: GET
  - action: readSocialNetWork
    path: /social-networks/{id:\d+}
    methods: GET
  - action: updateSocialNetWork
    path: /social-networks/edit/{id:\d+}
    methods: GET | POST
  - action: createSocialNetWork
    path: /social-networks/create
    methods: GET | POST
  - action: deleteSocialNetWork
    path: /social-networks/delete
    methods: POST
user:
  - action: login
    path: /login
    methods: GET | POST
  - action: signup
    path: /signup
    methods: GET | POST
  - action: logout
    path: /logout
    methods: GET

