index:
  - action: index
    path: /
    methods: GET
posts:
  - action: list
    path: '[/{page:[\d+]}]'
    methods: GET
  - action: show
    path: /{id:[a-z0-9-]+}
    methods: GET
admin:
  - action: index
    path: ''
    methods: GET
  - action: readPosts
    path: /posts
    methods: GET
  - action: createPost
    path: /posts/create
    methods: GET | POST
  - action: readPost
    path: /posts/{id:\d+}
    methods: GET
  - action: updatePost
    path: /posts/edit/{id:\d+}
    methods: GET | POST
  - action: deletePost
    path: /posts/delete
    methods: POST
  - action: listComments
    path: /comments
    methods: GET
  - action: showComment
    path: /comments/{id:\d+}
    methods: GET
  - action: editComment
    path: /comments/edit/{id:\d+}
    methods: GET
  - action: readUsers
    path: /users
    methods: GET
  - action: readUser
    path: /users/{id:\d+}
    methods: GET
  - action: updateUser
    path: /users/edit/{id:\d+}
    methods: GET | POST
  - action: deleteUser
    path: /users/delete
    methods: POST
user:
  - action: login
    path: /login
    methods: GET | POST
  - action: signup
    path: /signup
    methods: GET | POST
  - action: logout
    path: /logout
    methods: GET

